name: "Release Build"

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Add version to file
        run: mv auto-cli.bat auto-cli-${{ env.RELEASE_VERSION }}.bat
      - name: Publish the release
        run: |
          gh release create "${{ env.RELEASE_VERSION }}" \
          --title "${{ env.RELEASE_VERSION }}" \
          --generate-notes \
          auto-cli-${{ env.RELEASE_VERSION }}.bat
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: Clean working directory
        run: |
          git reset --hard HEAD
          git clean -f -d
      - name: Create and switch to a new branch
        run: |
          git checkout -b update-readme-${{ env.RELEASE_VERSION }}
        continue-on-error: true
      - name: Update the README link
        run: |
          sed -i -E 's/v[0-9]+\.[0-9]+/${{ env.RELEASE_VERSION }}/g' README.md
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add README.md
          git commit -m "Update README.md"
          git push origin update-readme-${{ env.RELEASE_VERSION }}
        continue-on-error: true
      - name: Force push updater to all and delete branch
        run: |
          git checkout update-readme-${{ env.RELEASE_VERSION }}
          git push origin --force update-readme-${{ env.RELEASE_VERSION }}:dev
          git push origin :update-readme-${{ env.RELEASE_VERSION }}
          git checkout dev
          git push origin --force dev:main
          